# Generated by Django 5.1.15 on 2026-09-20 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('official', 'Official'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('category', models.CharField(default='General', max_length=50)),
                ('author_title', models.CharField(default='Campus Administration', max_length=100)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('STEM', 'STEM'), ('Leadership', 'Leadership'), ('Creative Arts', 'Creative Arts'), ('Volunteering', 'Volunteering'), ('Culture', 'Culture')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('meeting_schedule', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('accent_color', models.CharField(default='bg-indigo-500/10 text-indigo-500 border-indigo-500/20', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Career', 'Career'), ('Arts', 'Arts'), ('Social', 'Social'), ('Academic', 'Academic'), ('Sports', 'Sports')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('featured', models.BooleanField(default=False)),
                ('image_gradient', models.CharField(default='from-indigo-600 to-blue-700', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('cancelled', 'Cancelled')], default='attending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
