# Generated by Django 5.1.15 on 2026-09-20 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1 seat.')]),
        ),
    ]
