# Generated by Django 5.1.15 on 2026-09-20 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_event_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banner_gradient',
            field=models.CharField(default='from-indigo-600 to-blue-700', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='membership_requires_approval',
            field=models.BooleanField(default=True, help_text='Whether joining this club requires leader approval.'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status',
            field=models.CharField(choices=[('attending', 'Attending'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], db_index=True, default='attending', max_length=20),
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('vice_president', 'Vice President'), ('president', 'President')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='campus.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['club', 'status'], name='campus_club_club_id_e7f569_idx'), models.Index(fields=['user', 'status'], name='campus_club_user_id_982e24_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'user'), name='unique_user_club_membership')],
            },
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('update', 'Update'), ('discussion', 'Discussion')], db_index=True, default='discussion', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_members_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_posts', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campus.club')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['club', '-is_pinned', '-created_at'], name='campus_club_club_id_b2ee83_idx')],
            },
        ),
    ]
