# Generated by Django 5.1.15 on 2026-09-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_club_banner_gradient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('announcement', 'Campus Announcement'), ('event_reminder', 'Event Reminder'), ('event_rsvp', 'Event RSVP'), ('waitlist_promotion', 'Waitlist Promotion'), ('club_application', 'Club Application'), ('club_application_approved', 'Club Application Approved'), ('club_application_rejected', 'Club Application Rejected'), ('club_post', 'Club Post'), ('system', 'System Alert')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.BooleanField(default=True)),
                ('event_reminders', models.BooleanField(default=True)),
                ('rsvp_updates', models.BooleanField(default=True)),
                ('waitlist_promotions', models.BooleanField(default=True)),
                ('club_activity', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('department', 'Specific Department'), ('graduation_year', 'Specific Graduation Year'), ('both', 'Department & Graduation Year')], db_index=True, default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['priority', 'is_published'], name='campus_anno_priorit_50135f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'is_published'], name='campus_anno_target__fba771_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['scheduled_at', 'expires_at'], name='campus_anno_schedul_bb9e74_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='campus.announcement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='campus.club'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='campus.event'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='campus_noti_recipie_0dec59_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='campus_noti_recipie_721561_idx'),
        ),
    ]
