# Generated by Django 5.1.15 on 2026-09-21 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_eventquestion_eventanswer_eventquestionupvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status', 'created_at'], name='campus_even_event_i_97387d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['event', 'status', 'is_checked_in'], name='campus_even_event_i_ef6daa_idx'),
        ),
    ]
