# Generated by Django 5.1.15 on 2026-09-26 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_eventrsvp_campus_even_event_i_97387d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tier', models.CharField(choices=[('Super Dream', 'Super Dream (>12 LPA)'), ('Dream', 'Dream (7-12 LPA)'), ('Tier 1', 'Tier 1 (4.5-7 LPA)'), ('Tier 2', 'Tier 2 (<4.5 LPA)')], default='Tier 1', max_length=30)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hod_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='published', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='published', help_text='Institutional lifecycle status', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=150)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('competition', 'Competition'), ('scholarship', 'Scholarship'), ('certification', 'Certification'), ('placement', 'Placement Opportunity')], db_index=True, default='internship', max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('stipend_or_prize', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField(db_index=True)),
                ('apply_url', models.CharField(blank=True, max_length=500)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='published', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campus.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_role', models.CharField(db_index=True, max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('package_lpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Compensation in Lakhs Per Annum (INR)', max_digits=5)),
                ('drive_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('application_deadline', models.DateTimeField(db_index=True)),
                ('eligibility_min_cgpa', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('eligibility_max_backlogs', models.PositiveIntegerField(default=0)),
                ('eligibility_departments', models.JSONField(default=list, help_text="List of eligible department codes e.g. ['CSE', 'ECE', 'CSM', 'CSD', 'IT']")),
                ('eligibility_graduation_year', models.PositiveIntegerField(default=2026, help_text='Eligible graduating batch year')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active / Applications Open'), ('in_progress', 'Drive in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=30)),
                ('venue_or_link', models.CharField(blank=True, max_length=255)),
                ('rounds_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='campus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-drive_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected / Offered'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30)),
                ('cgpa_at_application', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resume_url', models.URLField(blank=True, max_length=500)),
                ('status_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campus.placementdrive')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('venue_or_link', models.CharField(blank=True, max_length=255)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cleared', 'Cleared / Recommended'), ('failed', 'Not Cleared'), ('absent', 'Absent')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='campus.placementapplication')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('event', 'Event'), ('club', 'Club'), ('announcement', 'Announcement'), ('opportunity', 'Opportunity'), ('coordinator_request', 'Coordinator Request')], db_index=True, max_length=30)),
                ('item_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], db_index=True, default='pending', max_length=30)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', 'status'], name='campus_appr_item_ty_6289e1_idx'), models.Index(fields=['status', '-created_at'], name='campus_appr_status_8934e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='campus_audi_action_fa37ca_idx'), models.Index(fields=['resource_type', 'resource_id'], name='campus_audi_resourc_a9c217_idx'), models.Index(fields=['actor', 'created_at'], name='campus_audi_actor_i_f52cd0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type', 'status'], name='campus_oppo_opportu_9aa58a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline', 'status'], name='campus_oppo_deadlin_d69bc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunityapplication',
            constraint=models.UniqueConstraint(fields=('opportunity', 'student'), name='unique_student_opportunity_application'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['status', 'application_deadline'], name='campus_plac_status_7c3df0_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['eligibility_graduation_year', 'status'], name='campus_plac_eligibi_193e43_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['drive', 'status'], name='campus_plac_drive_i_641098_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['student', 'status'], name='campus_plac_student_36f631_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementapplication',
            constraint=models.UniqueConstraint(fields=('drive', 'student'), name='unique_student_drive_application'),
        ),
    ]
