# Generated by Django 5.2.17 on 2026-09-28 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_company_department_announcement_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status', 'category'], name='campus_club_status_4166eb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_time'], name='campus_even_status_3cb5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'start_time'], name='campus_even_club_id_ff9013_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user', 'status'], name='campus_even_user_id_615045_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['opportunity', 'status'], name='campus_oppo_opportu_beb4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['student', 'status'], name='campus_oppo_student_05ac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='placementdrive',
            index=models.Index(fields=['status', 'drive_date'], name='campus_plac_status_e6fd05_idx'),
        ),
    ]
