# Generated by Django 5.1.15 on 2026-09-26 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='backlogs',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_placed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('club_coordinator', 'Club Coordinator'), ('department_admin', 'Department Admin'), ('tpo_admin', 'TPO Admin'), ('college_admin', 'College Admin'), ('super_admin', 'Super Admin'), ('club_leader', 'Club Leader (Legacy)'), ('admin', 'Admin (Legacy)')], db_index=True, default='student', max_length=30),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('cabin_location', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_hod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'faculty profile',
                'verbose_name_plural': 'faculty profiles',
            },
        ),
    ]
