# Generated by Django 5.2.17 on 2026-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_backlogs_studentprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['department', 'graduation_year'], name='users_stude_departm_7e6dde_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['department', 'cgpa'], name='users_stude_departm_eb4f7d_idx'),
        ),
    ]
